[sim]
connections = "1"
delay = "50ms..200ms"
max_inflight = 1000
iterations = 1000
streams = 5
stream_data = 500000000

[report.tx-packets]
filters = ["conn.success", "conn.client"]
x = "net.delay"
y = "conn.tx.packets"

[report.lost-packets]
filters = ["conn.success", "conn.client"]
x = "net.delay"
y = "conn.lost.packets"

[report.tx-throughput]
filters = ["conn.success", "conn.client"]
x = "net.delay"
y = "conn.tx.stream-throughput"

[report.congestion-window]
filters = ["conn.success", "conn.client"]
x = "net.delay"
y = "conn.max-cwin"
